name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint with eslint
        run: yarn lint:eslint

      - name: Lint with markdownlint
        run: yarn lint:markdownlint

      - name: Lint with prettier
        run: yarn lint:prettier

      - name: Lint with tsc
        run: yarn lint:tsc

      - name: Lint with yarn-dedupe
        run: yarn lint:yarn-dedupe
